import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assignment 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            padding: "1px 20px",
            color: "var(--foreground)",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            transition: "background 0.5s ease, color 0.5s ease",
            borderRadius: "0x",
            borderBottom: "1px solid var(--foreground)"
          }}
        >
          <span style={{ fontWeight: "bold", fontSize: "25px"}}>Cloud-Web</span>
          <span>LTU ID: 22586650</span>
        </div>

        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
